# Generated by Django 5.2.14 on 2026-07-03 10:16

from django.db import migrations


def seed_pages(apps, schema_editor):
    pass

def reverse_seed(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_companydetails_alter_blog_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_pages, reverse_seed),
    ]
