# Generated by Django 5.2.14 on 2026-07-03 10:43

from django.db import migrations


def seed_pages(apps, schema_editor):
    pass

def reverse_seed(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_seed_default_pages'),
    ]

    operations = [
        migrations.RunPython(seed_pages, reverse_seed),
    ]
