# Generated by Django 5.2.3 on 2026-08-28 06:40

from django.db import migrations


def seed_modules(apps, schema_editor):
    UserGroup = apps.get_model('dashboard', 'UserGroup')
    Module = apps.get_model('dashboard', 'Module')
    Child = apps.get_model('dashboard', 'Child')
    Permission = apps.get_model('dashboard', 'Permission')

    admin_group, _ = UserGroup.objects.get_or_create(name='admin', defaults={'status': True})

    Module.objects.all().delete()

    modules_data = [
        {
            'name': 'Users', 'url_name': '', 'icon_class': 'bi bi-person', 'priority': 1,
            'children': [
                {'name': 'All Users', 'url_name': 'users_list'},
                {'name': 'Add User', 'url_name': 'create_user'},
            ]
        },
        {
            'name': 'Form Requests', 'url_name': '', 'icon_class': 'bi bi-person-badge', 'priority': 2,
            'children': [
                {'name': 'Contact', 'url_name': 'contact_requests'},
            ]
        },
        {
            'name': 'Usergroup', 'url_name': '', 'icon_class': 'bi bi-people', 'priority': 3,
            'children': [
                {'name': 'All Usergroups', 'url_name': 'usergroup'},
                {'name': 'Add Usergroup', 'url_name': 'add_usergroup'},
            ]
        },
        {
            'name': 'Blog', 'url_name': '', 'icon_class': 'bi bi-journal-text', 'priority': 4,
            'children': [
                {'name': 'All Posts', 'url_name': 'posts'},
                {'name': 'Add Post', 'url_name': 'add_post'},
                {'name': 'Categories', 'url_name': 'categories'},
            ]
        },
        {
            'name': 'Pages', 'url_name': '', 'icon_class': 'bi bi-file-earmark', 'priority': 5,
            'children': [
                {'name': 'All Pages', 'url_name': 'page_view'},
                {'name': 'Add Page', 'url_name': 'add_page'},
            ]
        },
        {
            'name': 'Gallery', 'url_name': '', 'icon_class': 'bi bi-image', 'priority': 6,
            'children': [
                {'name': 'All Gallery', 'url_name': 'gallery_view'},
                {'name': 'Add Gallery', 'url_name': 'add_gallery'},
            ]
        },
        {
            'name': 'File Manager', 'url_name': '', 'icon_class': 'bi bi-file-text', 'priority': 7,
            'children': [
                {'name': 'All Files', 'url_name': 'file_manager'},
                {'name': 'Add File', 'url_name': 'add_file'},
            ]
        }
    ]

    for data in modules_data:
        module = Module.objects.create(
            name=data['name'],
            url_name=data['url_name'],
            icon_class=data['icon_class'],
            priority=data['priority']
        )
        
        for child_data in data['children']:
            Child.objects.create(
                module=module,
                name=child_data['name'],
                url_name=child_data['url_name']
            )

        perm, _ = Permission.objects.get_or_create(usergroup=admin_group, module=module)
        perm.enabled = True
        perm.save()


def reverse_seed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_gallery_image'),
    ]

    operations = [
        migrations.RunPython(seed_modules, reverse_seed),
    ]
