# Generated by Django 5.2.3 on 2026-08-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_seed_dashboard_modules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingEnquiry',
        ),
    ]
