# Generated by Django 5.2.3 on 2026-08-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_delete_bookingenquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='meta_keywords',
        ),
        migrations.AddField(
            model_name='page',
            name='canonical_tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Canonical Tag'),
        ),
    ]
