# Generated by Django 5.2.3 on 2026-08-31 08:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_blog_blog_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('image', models.CharField(help_text='Paste image URL from File Manager/Gallery', max_length=500)),
                ('video_url', models.CharField(blank=True, help_text='Full YouTube Embed URL', max_length=500, null=True)),
                ('store_name', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('store_type', models.CharField(blank=True, max_length=200)),
                ('store_size', models.CharField(blank=True, max_length=100)),
                ('scope_of_project', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('store_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(help_text='Paste image URL from File Manager/Gallery', max_length=500)),
                ('video_id', models.CharField(blank=True, help_text='YouTube Video ID (e.g., Ym-lgWHk9AY)', max_length=100, null=True)),
                ('scope', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
